import { ForbiddenException, Injectable } from "@nestjs/common";
import { MongoService } from "../mongo/mongo.service.js";
import { ConfigManagementService, PipelineConfig } from "../config/config-management.service.js";
import { LogDocument } from "../logs/log-document.js";

export interface LoadTestDataRequest {
  pipeline?: Partial<PipelineConfig>;
  pipelineName?: string;
  logCount?: number;
}

export interface LoadTestDataResponse {
  pipeline: PipelineConfig;
  insertedLogs: number;
}

@Injectable()
export class TestDataService {
  constructor(
    private readonly mongo: MongoService,
    private readonly configManagement: ConfigManagementService,
  ) {}

  async load(request: LoadTestDataRequest = {}): Promise<LoadTestDataResponse> {
    if (process.env.LOGARYS_ENABLE_TEST_DATA_ENDPOINTS !== "true") {
      throw new ForbiddenException("Test data endpoints are disabled. Set LOGARYS_ENABLE_TEST_DATA_ENDPOINTS=true to enable them.");
    }

    const pipelineName = request.pipelineName ?? request.pipeline?.name ?? "logarys-test-pipeline";
    const logCount = Math.min(Math.max(request.logCount ?? 100, 1), 10000);

    const existing = await this.mongo.collection<PipelineConfig>("pipelines").findOne({
      $or: [{ id: pipelineName }, { name: pipelineName }],
    });

    const pipeline = existing ?? await this.configManagement.createPipeline({
      id: pipelineName,
      name: pipelineName,
      enabled: true,
      inputType: "http",
      description: "Test pipeline generated by console-manager",
      config: {
        source: "console-manager-test-data",
        format: "json",
      },
      ...(request.pipeline ?? {}),
    });

    const levels = ["debug", "info", "warning", "error", "critical"];
    const now = Date.now();
    const logs: LogDocument[] = Array.from({ length: logCount }, (_, index) => {
      const level = levels[index % levels.length];
      return {
        pipelineId: pipeline.id ?? pipeline.name,
        timestamp: new Date(now - (logCount - index) * 1000),
        level,
        source: "console-manager-test-data",
        service: index % 2 === 0 ? "checkout" : "catalog",
        environment: "dev",
        host: `dev-${(index % 4) + 1}`,
        message: `Synthetic ${level} log #${String(index + 1).padStart(3, "0")}`,
        normalizedMessage: `Synthetic ${level} log`,
        tags: ["test-data", level],
        context: {
          index: index + 1,
          requestId: `test-${String(index + 1).padStart(3, "0")}`,
          durationMs: 10 + index * 3,
        },
        raw: {
          generatedBy: "console-manager",
          index: index + 1,
        },
      };
    });

    if (logs.length > 0) {
      await this.mongo.collection<LogDocument>("logs").insertMany(logs);
    }

    await this.mongo.collection<LogDocument>("logs").createIndex({ pipelineId: 1, timestamp: -1 });
    await this.mongo.collection<LogDocument>("logs").createIndex({ level: 1, timestamp: -1 });
    await this.mongo.collection<LogDocument>("logs").createIndex({ message: "text", normalizedMessage: "text", source: "text", service: "text" });

    return {
      pipeline,
      insertedLogs: logs.length,
    };
  }
}
